
CREATE TABLE MUNICIPIO (
  ID INT PRIMARY KEY IDENTITY,
  CODIGO VARCHAR(8) NOT NULL,
  DESCRICAO VARCHAR(40) NOT NULL,
  UF VARCHAR(2) NOT NULL
)

CREATE TABLE PESSOA (
   ID INT PRIMARY KEY IDENTITY,
   NOME VARCHAR(60) NOT NULL,
   SOBRENOME VARCHAR(60) NOT NULL,
   CPF VARCHAR(11) NOT NULL,
   TELEFONE VARCHAR(15),
   DT_CADASTRO DATE NOT NULL,
   ID_MUNICIPIO INT NOT NULL
)

ALTER TABLE PESSOA ADD CONSTRAINT FK_MUNICIPIO_PESSOA FOREIGN KEY (ID_MUNICIPIO)     
    REFERENCES MUNICIPIO (ID)   


CREATE TABLE NCM (
  ID INT PRIMARY KEY IDENTITY,
  CODIGO VARCHAR(30) NOT NULL,
  DESCRICAO VARCHAR(60) NOT NULL
)

CREATE TABLE PRODUTO (
  ID INT PRIMARY KEY IDENTITY,
  CODIGO VARCHAR(30) NOT NULL,
  DESCRICAO VARCHAR(60) NOT NULL,
  ID_NCM INT NOT NULL
)
ALTER TABLE PRODUTO ADD CONSTRAINT FK_NCM_PRODUTO FOREIGN KEY (ID_NCM)     
    REFERENCES NCM (ID)   


CREATE TABLE NOTA_FISCAL (
  ID INT PRIMARY KEY IDENTITY,
  NR_NUMERO VARCHAR(10) NOT NULL,
  SERIE_SUBSERIE VARCHAR(3) NULL,
  TIPO_NF VARCHAR(1) NOT NULL,
  DT_ENTRADA_SAIDA DATETIME NOT NULL,
  VALOR_DESCONTO NUMERIC(14,2) NULL,
  VALOR_TOTAL NUMERIC(14,2) NOT NULL,
  ID_PESSOA INT NOT NULL
)

ALTER TABLE NOTA_FISCAL ADD CONSTRAINT FK_PESSOA_NOTA_FISCAL FOREIGN KEY (ID_PESSOA)     
    REFERENCES PESSOA (ID)   


CREATE TABLE TRIB_ICMS (
  ID INT PRIMARY KEY IDENTITY,
  CODIGO VARCHAR(3) NOT NULL,
  DESCRICAO VARCHAR(120) NOT NULL
)

CREATE TABLE NOTA_FISCAL_ITEM (
  ID INT PRIMARY KEY IDENTITY,
  ID_NOTA_FISCAL INT NOT NULL,
  ID_PRODUTO INT NOT NULL,
  VLR_UNIT NUMERIC(14,2) NOT NULL,
  QTDE NUMERIC(12,4) NOT NULL,
  VLR_TOTAL NUMERIC(14,2) NOT NULL,
  ID_TRIB_ICMS INT NOT NULL
)

ALTER TABLE NOTA_FISCAL_ITEM ADD CONSTRAINT FK_NOTA_FISCAL_NF_ITEM FOREIGN KEY (ID_NOTA_FISCAL)     
    REFERENCES NOTA_FISCAL (ID)   

ALTER TABLE NOTA_FISCAL_ITEM ADD CONSTRAINT FK_PRODUTO_NOTA_FISCAL_ITEM FOREIGN KEY (ID_PRODUTO)     
    REFERENCES PRODUTO (ID)

ALTER TABLE NOTA_FISCAL_ITEM ADD CONSTRAINT FK_TRIB_ICMS_NOTA_FISCAL_ITEM FOREIGN KEY (ID_TRIB_ICMS)     
    REFERENCES TRIB_ICMS (ID)

GO;